import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const apiUrl = String.fromEnvironment('API_URL', defaultValue: 'https://dallini-app.onrender.com');

void main() => runApp(const DalliniApp());

class DalliniApp extends StatelessWidget {
  const DalliniApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'ط¯ظ„ظ‘ظٹظ†ظٹ',
    locale: const Locale('ar'),
    theme: ThemeData(useMaterial3: true, fontFamily: 'sans', colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF123B68)), scaffoldBackgroundColor: const Color(0xFFF5F7FB)),
    home: const AppRoot(),
  );
}

class AppRoot extends StatefulWidget { const AppRoot({super.key}); @override State<AppRoot> createState() => _AppRootState(); }
class _AppRootState extends State<AppRoot> {
  bool loading = true, loggedIn = false;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final p = await SharedPreferences.getInstance(); if (!mounted) return; setState(() { loggedIn = p.getBool('logged_in') ?? false; loading = false; }); }
  @override Widget build(BuildContext context) { if (loading) return const Scaffold(body: Center(child: Text('ط¯ظ„ظ‘ظٹظ†ظٹ', style: TextStyle(fontSize: 32, fontWeight: FontWeight.w900)))); return loggedIn ? const MainShell() : LoginScreen(onLoggedIn: _load); }
}

class LoginScreen extends StatefulWidget { final VoidCallback onLoggedIn; const LoginScreen({super.key, required this.onLoggedIn}); @override State<LoginScreen> createState() => _LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen> {
  final phone = TextEditingController(), otp = TextEditingController(), name = TextEditingController(); bool sent = false, busy = false;
  Future<void> login() async {
    if (phone.text.trim().length < 9) { _msg('ط£ط¯ط®ظ„ ط±ظ‚ظ… ظ‡ط§طھظپ طµط­ظٹط­'); return; }
    if (!sent) { setState(() => sent = true); _msg('طھظ… ط¥ط±ط³ط§ظ„ ط±ظ…ط² ط§ظ„طھط­ظ‚ظ‚. ظپظٹ ظˆط¶ط¹ ط§ظ„ط§ط®طھط¨ط§ط± ط§ط³طھط®ط¯ظ… 123456'); return; }
    if (otp.text.trim() != '123456') { _msg('ط±ظ…ط² ط§ظ„طھط­ظ‚ظ‚ ط؛ظٹط± طµط­ظٹط­'); return; }
    setState(() => busy = true);
    try { final p = await SharedPreferences.getInstance(); await p.setBool('logged_in', true); await p.setString('phone', phone.text.trim()); await p.setString('name', name.text.trim().isEmpty ? 'ظ…ط³طھط®ط¯ظ… ط¯ظ„ظ‘ظٹظ†ظٹ' : name.text.trim()); await p.setString('auth_mode', 'demo'); if (!mounted) return; setState(() => busy = false); _msg('طھظ… ط§ظ„ط¯ط®ظˆظ„ ط¨ظ†ط¬ط§ط­'); widget.onLoggedIn(); }
    catch (_) { if (mounted) { setState(() => busy = false); _msg('طھط¹ط°ط± ط­ظپط¸ ط¨ظٹط§ظ†ط§طھ ط§ظ„ط¯ط®ظˆظ„'); } }
  }
  void _msg(String t) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(t))); }
  @override Widget build(BuildContext context) => Directionality(textDirection: TextDirection.rtl, child: Scaffold(body: SafeArea(child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(children: [const SizedBox(height: 50), const Text('ط¯ظ„ظ‘ظٹظ†ظٹ', style: TextStyle(fontSize: 40, fontWeight: FontWeight.w900, color: Color(0xFF123B68))), const SizedBox(height: 8), const Text('ط¹ظ†ط¯ظƒ ظ…ط´ظƒظ„ط©طں ط¯ظ„ظ‘ظٹظ†ظٹ ط¹ظ„ظ‰ ط§ظ„ط­ظ„.', style: TextStyle(fontSize: 17)), const SizedBox(height: 45), Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(children: [const Align(alignment: Alignment.centerRight, child: Text('طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„', style: TextStyle(fontSize: 24, fontWeight: FontWeight.w800))), const SizedBox(height: 18), TextField(controller: phone, keyboardType: TextInputType.phone, decoration: const InputDecoration(labelText: 'ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ', hintText: '07XXXXXXXXX', prefixText: '+964 ', border: OutlineInputBorder())), if (sent) ...[const SizedBox(height: 12), TextField(controller: otp, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'ط±ظ…ط² ط§ظ„طھط­ظ‚ظ‚', hintText: '123456', border: OutlineInputBorder())), const SizedBox(height: 12), TextField(controller: name, decoration: const InputDecoration(labelText: 'ط§ظ„ط§ط³ظ…', hintText: 'ط§ظƒطھط¨ ط§ط³ظ…ظƒ', border: OutlineInputBorder()))], const SizedBox(height: 18), SizedBox(width: double.infinity, child: FilledButton(onPressed: busy ? null : login, child: Padding(padding: const EdgeInsets.all(14), child: Text(busy ? 'ط¬ط§ط±ظٹ ط§ظ„ط¯ط®ظˆظ„...' : sent ? 'ط¯ط®ظˆظ„' : 'ط¥ط±ط³ط§ظ„ ط±ظ…ط² ط§ظ„طھط­ظ‚ظ‚')))), if (sent) TextButton(onPressed: () => setState(() => sent = false), child: const Text('طھط؛ظٹظٹط± ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ'))])))]))));
}

class MainShell extends StatefulWidget { const MainShell({super.key}); @override State<MainShell> createState() => _MainShellState(); }
class _MainShellState extends State<MainShell> { int index = 0; final pages = const [HomePage(), OrdersPage(), NewRequestPage(), MessagesPage(), ProfilePage()]; @override Widget build(BuildContext context) => Directionality(textDirection: TextDirection.rtl, child: Scaffold(body: pages[index], bottomNavigationBar: NavigationBar(selectedIndex: index, onDestinationSelected: (i) => setState(() => index = i), destinations: const [NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: 'ط§ظ„ط±ط¦ظٹط³ظٹط©'), NavigationDestination(icon: Icon(Icons.receipt_long_outlined), label: 'ط·ظ„ط¨ط§طھظٹ'), NavigationDestination(icon: Icon(Icons.add_circle_outline), label: 'ط·ظ„ط¨ ط¬ط¯ظٹط¯'), NavigationDestination(icon: Icon(Icons.chat_bubble_outline), label: 'ط§ظ„ظ…ط­ط§ط¯ط«ط§طھ'), NavigationDestination(icon: Icon(Icons.person_outline), label: 'ط­ط³ط§ط¨ظٹ')]))); }

class HomePage extends StatelessWidget { const HomePage({super.key}); @override Widget build(BuildContext context) { final cats = [['âڑ،','ظƒظ‡ط±ط¨ط§ط،'],['ًں’§','ط³ط¨ط§ظƒط©'],['â‌„ï¸ڈ','طھظƒظٹظٹظپ'],['ًں”§','طµظٹط§ظ†ط© ط£ط¬ظ‡ط²ط©'],['ًں§¹','طھظ†ط¸ظٹظپ'],['ًںڑ—','ط³ظٹط§ط±ط§طھ']]; return SafeArea(child: CustomScrollView(slivers: [SliverToBoxAdapter(child: Container(padding: const EdgeInsets.fromLTRB(20,28,20,25), decoration: const BoxDecoration(gradient: LinearGradient(colors: [Color(0xFF0D2B50),Color(0xFF1D558B)]), borderRadius: BorderRadius.vertical(bottom: Radius.circular(30))), child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('ط¯ظ„ظ‘ظٹظ†ظٹ',style: TextStyle(color: Colors.white,fontSize:30,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('ط¹ظ†ط¯ظƒ ظ…ط´ظƒظ„ط©طں ط¯ظ„ظ‘ظٹظ†ظٹ ط¹ظ„ظ‰ ط§ظ„ط­ظ„.',style:TextStyle(color:Colors.white70,fontSize:15)),SizedBox(height:16),Row(children:[Icon(Icons.location_on,color:Colors.white,size:19),SizedBox(width:5),Text('ط¨ط؛ط¯ط§ط¯',style:TextStyle(color:Colors.white))])])), SliverPadding(padding: const EdgeInsets.all(18), sliver: SliverList(delegate: SliverChildListDelegate([const Text('ط´ظ†ظˆ طھط­طھط§ط¬طں',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:12),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:cats.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:1.05),itemBuilder:(_,i)=>Card(child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>NewRequestPage(initialCategory:cats[i][1]))),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(cats[i][0],style:const TextStyle(fontSize:28)),const SizedBox(height:5),Text(cats[i][1],textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w700))])))),const SizedBox(height:22),const Text('ط®ط¯ظ…ط§طھ ظ‚ط±ظٹط¨ط© ظ…ظ†ظƒ',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),const ProviderCard()])))])); } }

class ProviderCard extends StatefulWidget { const ProviderCard({super.key}); @override State<ProviderCard> createState()=>_ProviderCardState(); }
class _ProviderCardState extends State<ProviderCard> { bool favorite=false; @override void initState(){super.initState();_load();} Future<void> _load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>favorite=p.getBool('favorite_ahmed')??false);} Future<void> _toggle()async{final p=await SharedPreferences.getInstance();await p.setBool('favorite_ahmed',!favorite);if(!mounted)return;setState(()=>favorite=!favorite);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(favorite?'طھظ…طھ ط§ظ„ط¥ط¶ط§ظپط© ظ„ظ„ظ…ظپط¶ظ„ظٹظ†':'طھظ…طھ ط§ظ„ط¥ط²ط§ظ„ط© ظ…ظ† ط§ظ„ظ…ظپط¶ظ„ظٹظ†')));} @override Widget build(BuildContext context)=>Card(child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProviderDetailsPage())),child:Padding(padding:const EdgeInsets.all(15),child:Row(children:[const CircleAvatar(radius:27,child:Text('ًں‘¨â€چًں”§',style:TextStyle(fontSize:25))),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('ط£ط­ظ…ط¯ ط¹ظ„ظٹ',style:TextStyle(fontWeight:FontWeight.w800,fontSize:16)),Text('âœ“ ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط© ظ…ظˆط«ظ‘ظ‚',style:TextStyle(color:Colors.green,fontSize:12)),SizedBox(height:4),Text('ظپظ†ظٹ طھظƒظٹظٹظپ â€¢ 2.4 ظƒظ… â€¢ ظ…طھط§ط­ ط§ظ„ط¢ظ†',style:TextStyle(color:Colors.grey,fontSize:12)),Text('âک… 4.8 â€¢ 312 طھظ‚ظٹظٹظ…',style:TextStyle(color:Color(0xFFB77900),fontSize:12))])),IconButton(onPressed:_toggle,icon:Icon(favorite?Icons.favorite:Icons.favorite_border))]))))); }
}

class ProviderDetailsPage extends StatefulWidget { const ProviderDetailsPage({super.key}); @override State<ProviderDetailsPage> createState()=>_ProviderDetailsPageState(); }
class _ProviderDetailsPageState extends State<ProviderDetailsPage>{bool favorite=false;@override void initState(){super.initState();_load();}Future<void>_load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>favorite=p.getBool('favorite_ahmed')??false);}Future<void>_toggle()async{final p=await SharedPreferences.getInstance();await p.setBool('favorite_ahmed',!favorite);if(mounted)setState(()=>favorite=!favorite);} @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ظ…ظ‚ط¯ظ… ط§ظ„ط®ط¯ظ…ط©')),body:ListView(padding:const EdgeInsets.all(18),children:[const CircleAvatar(radius:45,child:Text('ًں‘¨â€چًں”§',style:TextStyle(fontSize:38))),const SizedBox(height:12),const Center(child:Text('ط£ط­ظ…ط¯ ط¹ظ„ظٹ',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900))),const Center(child:Text('âœ“ ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط© ظ…ظˆط«ظ‘ظ‚ â€¢ ظپظ†ظٹ طھظƒظٹظٹظپ',style:TextStyle(color:Colors.green))),const SizedBox(height:18),Card(child:Column(children:const[ ListTile(leading:Icon(Icons.star),title:Text('4.8 ظ…ظ† 5'),subtitle:Text('312 طھظ‚ظٹظٹظ…')),ListTile(leading:Icon(Icons.location_on_outlined),title:Text('2.4 ظƒظ…'),subtitle:Text('ط¶ظ…ظ† ظ†ط·ط§ظ‚ ط¨ط؛ط¯ط§ط¯')),ListTile(leading:Icon(Icons.check_circle_outline),title:Text('ظ…طھط§ط­ ط§ظ„ط¢ظ†'),subtitle:Text('ظٹظ…ظƒظ†ظ‡ ط§ط³طھظ‚ط¨ط§ظ„ ط§ظ„ط·ظ„ط¨ط§طھ'))])),const SizedBox(height:12),FilledButton.icon(onPressed:_toggle,icon:Icon(favorite?Icons.favorite:Icons.favorite_border),label:Text(favorite?'ط¥ط²ط§ظ„ط© ظ…ظ† ط§ظ„ظ…ظپط¶ظ„ظٹظ†':'ط¥ط¶ط§ظپط© ظ„ظ„ظ…ظپط¶ظ„ظٹظ†')),OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const NewRequestPage(initialCategory:'طھظƒظٹظٹظپ'))),icon:const Icon(Icons.add),label:const Text('ط·ظ„ط¨ ط®ط¯ظ…ط© طھظƒظٹظٹظپ'))]));}

class NewRequestPage extends StatefulWidget { final String? initialCategory; const NewRequestPage({super.key,this.initialCategory}); @override State<NewRequestPage> createState()=>_NewRequestPageState(); }
class _NewRequestPageState extends State<NewRequestPage>{late String category;final desc=TextEditingController();bool busy=false;final categories=const['ظƒظ‡ط±ط¨ط§ط،','ط³ط¨ط§ظƒط©','طھظƒظٹظٹظپ','طµظٹط§ظ†ط© ط£ط¬ظ‡ط²ط©','طھظ†ط¸ظٹظپ','ط³ظٹط§ط±ط§طھ'];@override void initState(){super.initState();category=widget.initialCategory??'ظƒظ‡ط±ط¨ط§ط،';}
Future<void>submit()async{if(desc.text.trim().isEmpty){_msg('ط§ظƒطھط¨ ط§ظ„ظ…ط´ظƒظ„ط© ط£ظˆظ„ط§ظ‹');return;}setState(()=>busy=true);try{final r=await http.post(Uri.parse('$apiUrl/api/requests'),headers:{'Content-Type':'application/json'},body:jsonEncode({'category':category,'description':desc.text.trim(),'address':'ط¨ط؛ط¯ط§ط¯'})).timeout(const Duration(seconds:25));if(r.statusCode<200||r.statusCode>=300)throw Exception();final req=jsonDecode(r.body)as Map<String,dynamic>;await LocalData.addOrder(req);if(!mounted)return;await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('طھظ… ط¥ط±ط³ط§ظ„ ط§ظ„ط·ظ„ط¨ âœ“'),content:const Text('ط¨ط¯ط£ظ†ط§ ط§ظ„ط¨ط­ط« ط¹ظ† ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط© ظ…ظ†ط§ط³ط¨ ظ„ظ…ط´ظƒظ„طھظƒ.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('ط­ط³ظ†ظ‹ط§'))]));desc.clear();}catch(_){_msg('طھط¹ط°ط± ط¥ط±ط³ط§ظ„ ط§ظ„ط·ظ„ط¨. طھط­ظ‚ظ‚ ظ…ظ† ط§ظ„ط§طھطµط§ظ„ ط¨ط§ظ„ط®ط§ط¯ظ….');}finally{if(mounted)setState(()=>busy=false);}}
void _msg(String t){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));}
@override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('ط´ظ†ظˆ ط§ظ„ظ…ط´ظƒظ„ط©طں',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('ط§ظƒطھط¨ظ‡ط§ ط¨ط·ط±ظٹظ‚طھظƒطŒ ظ…ظˆ ظ„ط§ط²ظ… طھط¹ط±ظپ ط§ط³ظ… ط§ظ„ط®ط¯ظ…ط©.',style:TextStyle(color:Colors.grey)),const SizedBox(height:18),DropdownButtonFormField<String>(value:category,decoration:const InputDecoration(labelText:'ط§ظ„ظپط¦ط©',border:OutlineInputBorder()),items:categories.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>category=x!)),const SizedBox(height:12),TextField(controller:desc,maxLines:6,decoration:const InputDecoration(labelText:'ظˆطµظپ ط§ظ„ظ…ط´ظƒظ„ط©',hintText:'ظ…ط«ط§ظ„: ط§ظ„ظ…ظƒظٹظپ ظٹط´طھط؛ظ„ ط¨ط³ ط§ظ„ظ‡ظˆط§ ط­ط§ط±...',border:OutlineInputBorder())),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>_msg('ط§ظ„طھط³ط¬ظٹظ„ ط§ظ„طµظˆطھظٹ ط³ظٹط¶ط§ظپ ظپظٹ ط§ظ„ظ…ط±ط­ظ„ط© ط§ظ„طھط§ظ„ظٹط©'),icon:const Icon(Icons.mic),label:const Text('ط§ط­ع†ظٹ'))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:()=>_msg('ط§ظ„ظƒط§ظ…ظٹط±ط§ ط³ظٹط¶ط§ظپ ط¯ط¹ظ…ظ‡ط§ ظپظٹ ط§ظ„ظ…ط±ط­ظ„ط© ط§ظ„طھط§ظ„ظٹط©'),icon:const Icon(Icons.camera_alt_outlined),label:const Text('طµظˆظ‘ط±')))]),const SizedBox(height:16),FilledButton(onPressed:busy?null:submit,child:Padding(padding:const EdgeInsets.all(14),child:Text(busy?'ط¬ط§ط±ظٹ ط¥ط±ط³ط§ظ„ ط§ظ„ط·ظ„ط¨...':'ط¯ظ„ظ‘ظٹظ†ظٹ ط¹ظ„ظ‰ ط§ظ„ط­ظ„')))]));}
}

class LocalData { static Future<List<Map<String,dynamic>>>orders()async{final p=await SharedPreferences.getInstance();final raw=p.getString('local_orders');if(raw==null)return[];try{return(jsonDecode(raw)as List).map((e)=>Map<String,dynamic>.from(e as Map)).toList();}catch(_){return[];}}static Future<void>addOrder(Map<String,dynamic>o)async{final list=await orders();list.removeWhere((e)=>e['id'].toString()==o['id'].toString());list.insert(0,o);final p=await SharedPreferences.getInstance();await p.setString('local_orders',jsonEncode(list));}}

class OrdersPage extends StatefulWidget{const OrdersPage({super.key});@override State<OrdersPage>createState()=>_OrdersPageState();}
class _OrdersPageState extends State<OrdersPage>{bool loading=true;List<Map<String,dynamic>>orders=[];@override void initState(){super.initState();load();}Future<void>load()async{final local=await LocalData.orders();List<Map<String,dynamic>>remote=[];try{final r=await http.get(Uri.parse('$apiUrl/api/requests/mine')).timeout(const Duration(seconds:12));if(r.statusCode==200)remote=(jsonDecode(r.body)as List).map((e)=>Map<String,dynamic>.from(e as Map)).toList();}catch(_){}final merged=<String,Map<String,dynamic>>{};for(final o in[...local,...remote])merged[o['id'].toString()]=o;orders=merged.values.toList();orders.sort((a,b)=>(b['created_at']??'').toString().compareTo((a['created_at']??'').toString()));if(mounted)setState(()=>loading=false);}
String statusLabel(String s)=>const{'matching':'ط¬ط§ط±ظٹ ط§ظ„ط¨ط­ط«','accepted':'طھظ… ظ‚ط¨ظˆظ„ ط§ظ„ط·ظ„ط¨','on_way':'ظپظٹ ط§ظ„ط·ط±ظٹظ‚','arrived':'ظˆطµظ„ ظ…ظ‚ط¯ظ… ط§ظ„ط®ط¯ظ…ط©','in_progress':'ظ‚ظٹط¯ ط§ظ„طھظ†ظپظٹط°','completed':'ظ…ظƒطھظ…ظ„','cancelled':'ظ…ظ„ط؛ظ‰'}[s]??s;
@override Widget build(BuildContext context)=>SafeArea(child:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(18),children:[const Text('ط·ظ„ط¨ط§طھظٹ',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:12),if(loading)const Center(child:CircularProgressIndicator()),if(!loading&&orders.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(20),child:Text('ظ„ط§ طھظˆط¬ط¯ ط·ظ„ط¨ط§طھ ط­ط§ظ„ظٹط§ظ‹. ط¹ظ†ط¯ ط¥ط±ط³ط§ظ„ ط·ظ„ط¨ ط³ظٹط¸ظ‡ط± ظ‡ظ†ط§.'))),...orders.map((o)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.build_outlined)),title:Text((o['category']??'ط®ط¯ظ…ط©').toString()),subtitle:Text((o['description']??'').toString(),maxLines:2,overflow:TextOverflow.ellipsis),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(statusLabel((o['status']??'matching').toString()),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700)),const Icon(Icons.chevron_left)]),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderDetailsPage(order:o)))))])));}
}

class OrderDetailsPage extends StatefulWidget{final Map<String,dynamic>order;const OrderDetailsPage({super.key,required this.order});@override State<OrderDetailsPage>createState()=>_OrderDetailsPageState();}
class _OrderDetailsPageState extends State<OrderDetailsPage>{late Map<String,dynamic>order;bool cancelling=false;@override void initState(){super.initState();order=Map<String,dynamic>.from(widget.order);}String statusLabel(String s)=>const{'matching':'ط¬ط§ط±ظٹ ط§ظ„ط¨ط­ط« ط¹ظ† ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط©','accepted':'طھظ… ظ‚ط¨ظˆظ„ ط§ظ„ط·ظ„ط¨','on_way':'ظ…ظ‚ط¯ظ… ط§ظ„ط®ط¯ظ…ط© ظپظٹ ط§ظ„ط·ط±ظٹظ‚','arrived':'ظˆطµظ„ ظ…ظ‚ط¯ظ… ط§ظ„ط®ط¯ظ…ط©','in_progress':'ط§ظ„ط¹ظ…ظ„ ظ‚ظٹط¯ ط§ظ„طھظ†ظپظٹط°','completed':'طھظ… ط¥ظ†ط¬ط§ط² ط§ظ„ط·ظ„ط¨','cancelled':'طھظ… ط¥ظ„ط؛ط§ط، ط§ظ„ط·ظ„ط¨'}[s]??s;Future<void>cancel()async{setState(()=>cancelling=true);try{final id=order['id'].toString();try{await http.post(Uri.parse('$apiUrl/api/requests/$id/cancel')).timeout(const Duration(seconds:10));}catch(_){}order['status']='cancelled';await LocalData.addOrder(order);if(mounted)setState((){});}finally{if(mounted)setState(()=>cancelling=false);}}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('طھظپط§طµظٹظ„ ط§ظ„ط·ظ„ط¨')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((order['category']??'ط®ط¯ظ…ط©').toString(),style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(statusLabel((order['status']??'matching').toString()),style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:14),const Text('ظˆطµظپ ط§ظ„ظ…ط´ظƒظ„ط©',style:TextStyle(fontWeight:FontWeight.w800)),Text((order['description']??'').toString()),const SizedBox(height:14),const Text('ط§ظ„ظ…ظˆظ‚ط¹',style:TextStyle(fontWeight:FontWeight.w800)),Text((order['address']??'ط¨ط؛ط¯ط§ط¯').toString()),if((order['created_at']??'').toString().isNotEmpty)...[const SizedBox(height:14),const Text('ظˆظ‚طھ ط¥ظ†ط´ط§ط، ط§ظ„ط·ظ„ط¨',style:TextStyle(fontWeight:FontWeight.w800)),Text((order['created_at']??'').toString())]]))),const SizedBox(height:10),Card(child:ListTile(leading:const Icon(Icons.auto_awesome),title:const Text('ظ…ط³ط§ط¹ط¯ط© ط¯ظ„ظ‘ظٹظ†ظٹ'),subtitle:Text((order['ai_suggestion']??'ظ†ط¨ط­ط« ط¹ظ† ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط© ظ…ظ†ط§ط³ط¨ ظ„ظ…ط´ظƒظ„طھظƒ.').toString()))),const SizedBox(height:10),if((order['status']??'matching')!='completed'&&(order['status']??'matching')!='cancelled')OutlinedButton.icon(onPressed:cancelling?null:cancel,icon:const Icon(Icons.cancel_outlined),label:Text(cancelling?'ط¬ط§ط±ظٹ ط§ظ„ط¥ظ„ط؛ط§ط،...':'ط¥ظ„ط؛ط§ط، ط§ظ„ط·ظ„ط¨'))]));}
}

class MessagesPage extends StatelessWidget{const MessagesPage({super.key});@override Widget build(BuildContext context)=>const SafeArea(child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.chat_bubble_outline,size:55,color:Color(0xFF123B68)),SizedBox(height:12),Text('ط§ظ„ظ…ط­ط§ط¯ط«ط§طھ',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),SizedBox(height:6),Text('ط³طھط¸ظ‡ط± ظ…ط­ط§ط¯ط«ط§طھظƒ ظ…ط¹ ظ…ظ‚ط¯ظ…ظٹ ط§ظ„ط®ط¯ظ…ط© ظ‡ظ†ط§.')])));}

class ProfilePage extends StatefulWidget{const ProfilePage({super.key});@override State<ProfilePage>createState()=>_ProfilePageState();}
class _ProfilePageState extends State<ProfilePage>{String name='ظ…ط³طھط®ط¯ظ… ط¯ظ„ظ‘ظٹظ†ظٹ',phone='';@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();if(mounted)setState((){name=p.getString('name')??'ظ…ط³طھط®ط¯ظ… ط¯ظ„ظ‘ظٹظ†ظٹ';phone=p.getString('phone')??'';});}Future<void>editProfile()async{final n=TextEditingController(text:name),ph=TextEditingController(text:phone);final v=await showDialog<List<String>>(context:context,builder:(_)=>AlertDialog(title:const Text('طھط¹ط¯ظٹظ„ ط§ظ„ظ…ظ„ظپ ط§ظ„ط´ط®طµظٹ'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'ط§ظ„ط§ط³ظ…')),const SizedBox(height:10),TextField(controller:ph,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('ط¥ظ„ط؛ط§ط،')),FilledButton(onPressed:()=>Navigator.pop(context,[n.text.trim(),ph.text.trim()]),child:const Text('ط­ظپط¸'))]));if(v==null||v[0].isEmpty)return;final p=await SharedPreferences.getInstance();await p.setString('name',v[0]);await p.setString('phone',v[1]);if(mounted)setState((){name=v[0];phone=v[1];});}
Future<void>logout()async{final yes=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('طھط³ط¬ظٹظ„ ط§ظ„ط®ط±ظˆط¬'),content:const Text('ظ‡ظ„ طھط±ظٹط¯ طھط³ط¬ظٹظ„ ط§ظ„ط®ط±ظˆط¬ ظ…ظ† ط¯ظ„ظ‘ظٹظ†ظٹطں'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('ظ„ط§')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('ظ†ط¹ظ…'))]));if(yes!=true)return;final p=await SharedPreferences.getInstance();await p.setBool('logged_in',false);if(!mounted)return;Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>LoginScreen(onLoggedIn:()=>Navigator.of(context).pushReplacement(MaterialPageRoute(builder:(_)=>const MainShell())))),(_)=>false);}
@override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('ط­ط³ط§ط¨ظٹ',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:12),Card(child:ListTile(leading:const CircleAvatar(radius:27,child:Icon(Icons.person)),title:Text(name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(phone.isEmpty?'ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ ط؛ظٹط± ظ…ط­ظپظˆط¸':'+964 $phone'),trailing:IconButton(onPressed:editProfile,icon:const Icon(Icons.edit_outlined)))),const SizedBox(height:8),_row(Icons.receipt_long_outlined,'ط·ظ„ط¨ط§طھظٹ',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OrdersPage()))),_row(Icons.location_on_outlined,'ط¹ظ†ط§ظˆظٹظ†ظٹ',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AddressesPage()))),_row(Icons.favorite_border,'ظ…ظ‚ط¯ظ…ظˆ ط§ظ„ط®ط¯ظ…ط© ط§ظ„ظ…ظپط¶ظ„ظˆظ†',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const FavoritesPage()))),_row(Icons.notifications_none,'ط§ظ„ط¥ط´ط¹ط§ط±ط§طھ',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const NotificationsPage()))),_row(Icons.settings_outlined,'ط§ظ„ط¥ط¹ط¯ط§ط¯ط§طھ',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SettingsPage()))),_row(Icons.security_outlined,'ط§ظ„ط£ظ…ط§ظ† ظˆط§ظ„ط®طµظˆطµظٹط©',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SecurityPage()))),_row(Icons.help_outline,'ط§ظ„ظ…ط³ط§ط¹ط¯ط©',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const HelpPage()))),const SizedBox(height:12),OutlinedButton.icon(onPressed:logout,icon:const Icon(Icons.logout,color:Colors.red),label:const Text('طھط³ط¬ظٹظ„ ط§ظ„ط®ط±ظˆط¬',style:TextStyle(color:Colors.red))]));}
Widget _row(IconData i,String t,VoidCallback f)=>Card(child:ListTile(onTap:f,leading:Icon(i,color:const Color(0xFF123B68)),title:Text(t),trailing:const Icon(Icons.chevron_left)));}

class AddressesPage extends StatefulWidget{const AddressesPage({super.key});@override State<AddressesPage>createState()=>_AddressesPageState();}
class _AddressesPageState extends State<AddressesPage>{List<String>addresses=[];@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>addresses=p.getStringList('addresses')??[]);}Future<void>save()async{final p=await SharedPreferences.getInstance();await p.setStringList('addresses',addresses);}Future<void>addAddress()async{final c=TextEditingController();final v=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('ط¥ط¶ط§ظپط© ط¹ظ†ظˆط§ظ†'),content:TextField(controller:c,maxLines:2,decoration:const InputDecoration(labelText:'ط§ظ„ط¹ظ†ظˆط§ظ†',hintText:'ظ…ط«ط§ظ„: ط¨ط؛ط¯ط§ط¯طŒ ط§ظ„ظ…ظ†طµظˆط±طŒ ط´ط§ط±ط¹ ...',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('ط¥ظ„ط؛ط§ط،')),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('ط¥ط¶ط§ظپط©'))]));if(v==null||v.isEmpty)return;setState(()=>addresses.add(v));await save();}Future<void>remove(int i)async{setState(()=>addresses.removeAt(i));await save();}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ط¹ظ†ط§ظˆظٹظ†ظٹ')),body:ListView(padding:const EdgeInsets.all(18),children:[if(addresses.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('ظ„ط§ طھظˆط¬ط¯ ط¹ظ†ط§ظˆظٹظ† ظ…ط­ظپظˆط¸ط©. ط£ط¶ظپ ط¹ظ†ظˆط§ظ†ظ‹ط§ ظ„ط§ط³طھط®ط¯ط§ظ…ظ‡ ط¹ظ†ط¯ ط¥ط±ط³ط§ظ„ ط§ظ„ط·ظ„ط¨ط§طھ.'))),...addresses.asMap().entries.map((e)=>Card(child:ListTile(leading:const Icon(Icons.location_on_outlined),title:Text(e.value),trailing:IconButton(onPressed:()=>remove(e.key),icon:const Icon(Icons.delete_outline))))),FilledButton.icon(onPressed:addAddress,icon:const Icon(Icons.add),label:const Text('ط¥ط¶ط§ظپط© ط¹ظ†ظˆط§ظ†'))]));}

class FavoritesPage extends StatefulWidget{const FavoritesPage({super.key});@override State<FavoritesPage>createState()=>_FavoritesPageState();}
class _FavoritesPageState extends State<FavoritesPage>{bool favorite=false;@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>favorite=p.getBool('favorite_ahmed')??false);}Future<void>remove()async{final p=await SharedPreferences.getInstance();await p.setBool('favorite_ahmed',false);if(mounted)setState(()=>favorite=false);}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ظ…ظ‚ط¯ظ…ظˆ ط§ظ„ط®ط¯ظ…ط© ط§ظ„ظ…ظپط¶ظ„ظˆظ†')),body:ListView(padding:const EdgeInsets.all(18),children:[if(!favorite)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('ظ„ط§ ظٹظˆط¬ط¯ ظ…ظ‚ط¯ظ…ظˆ ط®ط¯ظ…ط© ظپظٹ ط§ظ„ظ…ظپط¶ظ„ط©. ظٹظ…ظƒظ†ظƒ ط§ظ„ط¶ط؛ط· ط¹ظ„ظ‰ â‌¤ï¸ڈ ظ„ط¥ط¶ط§ظپط© ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط©.'))),if(favorite)Card(child:ListTile(leading:const CircleAvatar(child:Text('ًں‘¨â€چًں”§')),title:const Text('ط£ط­ظ…ط¯ ط¹ظ„ظٹ'),subtitle:const Text('ظپظ†ظٹ طھظƒظٹظٹظپ â€¢ âک… 4.8 â€¢ ظ…ظˆط«ظ‘ظ‚'),trailing:IconButton(onPressed:remove,icon:const Icon(Icons.favorite,color:Colors.red)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProviderDetailsPage()))))]));}

class NotificationsPage extends StatefulWidget{const NotificationsPage({super.key});@override State<NotificationsPage>createState()=>_NotificationsPageState();}
class _NotificationsPageState extends State<NotificationsPage>{bool push=true,updates=true,offers=true;@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();if(mounted)setState((){push=p.getBool('notify_push')??true;updates=p.getBool('notify_updates')??true;offers=p.getBool('notify_offers')??true;});}Future<void>setValue(String k,bool v)async{final p=await SharedPreferences.getInstance();await p.setBool(k,v);}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ط§ظ„ط¥ط´ط¹ط§ط±ط§طھ')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Column(children:[SwitchListTile(title:const Text('ط¥ط´ط¹ط§ط±ط§طھ ط§ظ„ط·ظ„ط¨ط§طھ'),subtitle:const Text('ط­ط§ظ„ط© ط§ظ„ط·ظ„ط¨ ظˆط§ظ„ط¹ط±ظˆط¶ ط§ظ„ط¬ط¯ظٹط¯ط©'),value:push,onChanged:(v){setState(()=>push=v);setValue('notify_push',v);}),SwitchListTile(title:const Text('طھط­ط¯ظٹط«ط§طھ ط§ظ„ط·ظ„ط¨'),subtitle:const Text('ظˆطµظˆظ„ ظ…ظ‚ط¯ظ… ط§ظ„ط®ط¯ظ…ط© ظˆط¨ط¯ط، ط§ظ„ط¹ظ…ظ„'),value:updates,onChanged:(v){setState(()=>updates=v);setValue('notify_updates',v);}),SwitchListTile(title:const Text('ط§ظ„ط¹ط±ظˆط¶ ظˆط§ظ„طھظ†ط¨ظٹظ‡ط§طھ'),value:offers,onChanged:(v){setState(()=>offers=v);setValue('notify_offers',v);})]))]));}

class SettingsPage extends StatefulWidget{const SettingsPage({super.key});@override State<SettingsPage>createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{bool confirm=true,saveHistory=true;@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();if(mounted)setState((){confirm=p.getBool('confirm_send')??true;saveHistory=p.getBool('save_history')??true;});}Future<void>setValue(String k,bool v)async{final p=await SharedPreferences.getInstance();await p.setBool(k,v);}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ط§ظ„ط¥ط¹ط¯ط§ط¯ط§طھ')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Column(children:[const ListTile(title:Text('ط§ظ„ظ„ط؛ط©'),subtitle:Text('ط§ظ„ط¹ط±ط¨ظٹط©')),SwitchListTile(title:const Text('طھط£ظƒظٹط¯ ظ‚ط¨ظ„ ط¥ط±ط³ط§ظ„ ط§ظ„ط·ظ„ط¨'),value:confirm,onChanged:(v){setState(()=>confirm=v);setValue('confirm_send',v);}),SwitchListTile(title:const Text('ط­ظپط¸ ط³ط¬ظ„ ط§ظ„ط·ظ„ط¨ط§طھ ط¹ظ„ظ‰ ط§ظ„ط¬ظ‡ط§ط²'),value:saveHistory,onChanged:(v){setState(()=>saveHistory=v);setValue('save_history',v);})])),const Card(child:ListTile(leading:Icon(Icons.info_outline),title:Text('ط¥طµط¯ط§ط± ط§ظ„طھط·ط¨ظٹظ‚'),subtitle:Text('ط¯ظ„ظ‘ظٹظ†ظٹ 1.0.2')))]));}

class SecurityPage extends StatefulWidget{const SecurityPage({super.key});@override State<SecurityPage>createState()=>_SecurityPageState();}
class _SecurityPageState extends State<SecurityPage>{bool hidePhone=false,localLock=false;@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();if(mounted)setState((){hidePhone=p.getBool('hide_phone')??false;localLock=p.getBool('local_lock')??false;});}Future<void>setValue(String k,bool v)async{final p=await SharedPreferences.getInstance();await p.setBool(k,v);}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ط§ظ„ط£ظ…ط§ظ† ظˆط§ظ„ط®طµظˆطµظٹط©')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Column(children:[SwitchListTile(title:const Text('ط¥ط®ظپط§ط، ط±ظ‚ظ… ط§ظ„ظ‡ط§طھظپ ظپظٹ ط§ظ„ظ…ظ„ظپ'),value:hidePhone,onChanged:(v){setState(()=>hidePhone=v);setValue('hide_phone',v);}),SwitchListTile(title:const Text('ظ‚ظپظ„ ظ…ط­ظ„ظٹ ظ„ظ„طھط·ط¨ظٹظ‚'),subtitle:const Text('ط¥ط¹ط¯ط§ط¯ طھط¬ط±ظٹط¨ظٹ ط³ظٹظڈط±ط¨ط· ط¨ط§ظ„ط¨طµظ…ط©/ط±ظ…ط² ط§ظ„ط¬ظ‡ط§ط² ظ„ط§ط­ظ‚ظ‹ط§'),value:localLock,onChanged:(v){setState(()=>localLock=v);setValue('local_lock',v);})])),const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('ط§ظ„ط®طµظˆطµظٹط©: ظٹط³طھط®ط¯ظ… ط§ظ„طھط·ط¨ظٹظ‚ ط§ظ„ط¨ظٹط§ظ†ط§طھ ط§ظ„ظ„ط§ط²ظ…ط© ظ„طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„ ظˆط¥ط¯ط§ط±ط© ط§ظ„ط·ظ„ط¨ط§طھ ظˆط§ظ„ط¹ظ†ط§ظˆظٹظ† ظˆط§ظ„ظ…ظپط¶ظ„ط©.')))]));}

class HelpPage extends StatelessWidget{const HelpPage({super.key});@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('ط§ظ„ظ…ط³ط§ط¹ط¯ط©')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('ط§ظ„ط£ط³ط¦ظ„ط© ط§ظ„ط´ط§ط¦ط¹ط©',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),_faq('ط´ظ„ظˆظ† ط£ط±ط³ظ„ ط·ظ„ط¨طں','ط§ط®طھط± ط§ظ„ظپط¦ط© ط£ظˆ ط§ظپطھط­ آ«ط·ظ„ط¨ ط¬ط¯ظٹط¯آ»طŒ ط§ظƒطھط¨ ط§ظ„ظ…ط´ظƒظ„ط© ظˆط§ط¶ط؛ط· آ«ط¯ظ„ظ‘ظٹظ†ظٹ ط¹ظ„ظ‰ ط§ظ„ط­ظ„آ».') ,_faq('ظˆظٹظ† ط£ط´ظˆظپ ط·ظ„ط¨ط§طھظٹطں','ظ…ظ† آ«ط·ظ„ط¨ط§طھظٹآ» ظپظٹ ط§ظ„ط´ط±ظٹط· ط§ظ„ط³ظپظ„ظٹ ط£ظˆ ظ…ظ† ط­ط³ط§ط¨ظٹ > ط·ظ„ط¨ط§طھظٹ. ط§ط¶ط؛ط· ط¹ظ„ظ‰ ط£ظٹ ط·ظ„ط¨ ظ„ظپطھط­ ط§ظ„طھظپط§طµظٹظ„.'),_faq('ط´ظ„ظˆظ† ط£ط­ظپط¸ ظ…ظ‚ط¯ظ… ط®ط¯ظ…ط©طں','ط§ط¶ط؛ط· â‌¤ï¸ڈ ط¨ط¬ط§ظ†ط¨ ظ…ظ‚ط¯ظ… ط§ظ„ط®ط¯ظ…ط©طŒ ظˆط³طھط¬ط¯ظ‡ ظپظٹ ط­ط³ط§ط¨ظٹ > ظ…ظ‚ط¯ظ…ظˆ ط§ظ„ط®ط¯ظ…ط© ط§ظ„ظ…ظپط¶ظ„ظˆظ†.'),_faq('ط´ظ„ظˆظ† ط£ط¶ظٹظپ ط¹ظ†ظˆط§ظ†طں','ظ…ظ† ط­ط³ط§ط¨ظٹ > ط¹ظ†ط§ظˆظٹظ†ظٹطŒ ط«ظ… ط§ط¶ط؛ط· آ«ط¥ط¶ط§ظپط© ط¹ظ†ظˆط§ظ†آ».'),_faq('ظ‡ظ„ ط§ظ‚طھط±ط§ط­ ط§ظ„ط°ظƒط§ط، ط§ظ„ط§طµط·ظ†ط§ط¹ظٹ طھط´ط®ظٹطµ ظ†ظ‡ط§ط¦ظٹطں','ظ„ط§. ط§ظ„ط§ظ‚طھط±ط§ط­ ط¥ط±ط´ط§ط¯ظٹ ظˆظ„ظٹط³ طھط´ط®ظٹطµظ‹ط§ ظ†ظ‡ط§ط¦ظٹظ‹ط§طŒ ظˆظٹط¬ط¨ ط§ظ„ط§ط¹طھظ…ط§ط¯ ط¹ظ„ظ‰ ظپظ†ظٹ ظ…ط®طھطµ ط¹ظ†ط¯ ط§ظ„ط­ط§ط¬ط©.') ]));static Widget _faq(String q,String a)=>Card(child:ExpansionTile(title:Text(q,style:const TextStyle(fontWeight:FontWeight.w700)),childrenPadding:const EdgeInsets.fromLTRB(18,0,18,18),children:[Text(a)]));}
